[config]
skip_core_tasks = true

[tasks.clean]
script = [
"""
dist="./dist"
[ -d $dist ] \
  && find $dist -maxdepth 1 ! -path $dist | xargs -r rm -r \
  || :

pub="./public"
[ -d $pub ] \
  && find $pub -maxdepth 1 ! -path $pub  ! -path $pub/base.html ! -path $pub/main.css ! -path $pub/swiper.css ! -path $pub/ksact2_75 | xargs -r rm -r \
  || :
"""
]

[tasks.copy]
script = [
"""
dist="./dist"
pub="./public"

cp $dist/laymic.iife.js $pub
cp $dist/laymic.css $pub

cat $pub/base.html \
  | sed -e 's/{{$date}}/'$(date +%s)'/g' \
  > $pub/index.html
"""
]

[tasks.rollup]
command = "yarn"
args = ["run", "rollup", "-c"]

[tasks.rollup_prod]
env = {"NODE_ENV" = "production"}
command = "yarn"
args = ["run", "rollup", "-c"]

[tasks.postcss]
command = "yarn"
args = ["run", "postcss", "./src/css/laymic.css", "-o", "./dist/laymic.css"]

[tasks.postcss_prod]
env = {"NODE_ENV" = "production"}
command = "yarn"
args = ["run", "postcss", "./src/css/laymic.css", "-o", "./dist/laymic.min.css"]

[tasks.test]
command = "yarn"
args = ["run", "jest"]

[tasks.build_dev]
dependencies = [
  "rollup",
  "postcss"
]

[tasks.build_prod]
dependencies = [
  "rollup_prod",
  "postcss_prod"
]

[tasks.build]
dependencies = [
  "clean",
  "build_dev",
  "build_prod"
]

[tasks.serve]
command = "yarn"
args = ["run", "http-server", "./public", "-p", "8931"]
dependencies = [
  "build_dev",
  "copy"
]
